### ISSUE TITLE
[Forge 1.16.4] Server hangs when the same cave tries to generate

### ISSUE THREAD

**Issue by PantsWP** [yungnickyoung/Better-Caves#102]
Mod version: 1,16.3-1.0.6
Forge version: 35.1.13

Whenever a specific cave is loaded, it tries to generate but then the server freezes and the world will stop working. The player who has built her base in the same chunk(s) cannot join as a result. However, the chat will run just fine. The server has to be forcefully killed. It runs fine whenever the problematic area is not loaded otherwise. 

As the server does not crash, it doesn't generate a crash report. However, I can provide a debug log:
[debug.log](https://github.com/yungnickyoung/YUNGs-Better-Caves/files/5792294/debug.log)

Also, a list of every mod installed on the server:
![image](https://user-images.githubusercontent.com/1592219/104115467-9fa01880-535f-11eb-9dbf-643783b749e5.png)
![image](https://user-images.githubusercontent.com/1592219/104115480-cd855d00-535f-11eb-8ae1-673c35b61eec.png)
![image](https://user-images.githubusercontent.com/1592219/104115489-eaba2b80-535f-11eb-9176-0f9cf706b915.png)
![image](https://user-images.githubusercontent.com/1592219/104115582-ba26c180-5360-11eb-9c50-611993619fa2.png)
![image](https://user-images.githubusercontent.com/1592219/104115595-cc086480-5360-11eb-882e-d4cdbc0a45e9.png)
![image](https://user-images.githubusercontent.com/1592219/104115615-f9551280-5360-11eb-8580-245d76da8b77.png)

**Comment by CorgiTaco** [comment]
```
java.lang.NullPointerException: null
	at net.minecraft.world.lighting.SectionLightStorage.func_215521_h(SourceFile:96) ~[?:?]
	at net.minecraft.world.lighting.LightEngine.func_215471_c(LightEngine.java:129) ~[?:?]
	at net.minecraft.world.lighting.LevelBasedGraph.func_215469_a(LevelBasedGraph.java:122) ~[?:?]
	at net.minecraft.world.lighting.BlockLightEngine.func_215623_a(BlockLightEngine.java:118) ~[?:?]
	at net.minecraft.world.lighting.WorldLightManager.func_215573_a(SourceFile:41) ~[?:?]
	at net.minecraft.world.server.ServerWorldLightManager.func_215579_a(SourceFile:135) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384) ~[?:1.8.0_262]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647) ~[?:1.8.0_262]
	at net.minecraft.world.server.ServerWorldLightManager.func_223117_a(SourceFile:135) ~[?:?]
	at net.minecraft.world.server.ServerWorldLightManager.func_215603_b(SourceFile:170) ~[?:?]
	at net.minecraft.world.server.ServerWorldLightManager.func_223124_c(SourceFile:155) ~[?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:94) ~[?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:137) ~[?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:105) ~[?:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_262]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_262]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_262]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_262]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:163) [?:1.8.0_262]
```
	
Looks to me like the lighting thread was killed, and I see you have both BYG & Resourceful bees installed, I'm gonna take a shot in the dark and suggest you use byg 1.1.6 as opposed to 1.1.5 bc I fixed an issue similar to this in 1.1.6.

**Comment by yungnickyoung** [comment]
Yeah unfortunately I can't help you much here, but it's almost certainly the fault of another mod. I suggest trying what CorgiTaco mentioned and seeing if the issue persists. If so, check out the Discords/issue trackers of other mods you suspect and see if they know anything about it.

**Comment by ghost** [comment]
Hi I am having the same issue here - I dont think its yung's caves either, as it occurs even in an already loaded chunk for me - and on the server side it shows up as well as the client - Any help from OP would be appreciated if he discovers the problem
