### ISSUE TITLE
Could not execute entrypoint stage 'main' due to errors, provided by 'bettercaves'!

### ISSUE THREAD

**Issue by ClosedTheDor** [yungnickyoung/Better-Caves#132]
hi i have a problem 
before when i play minecraf that dosen't crash my game but now i can't play because of this 

---- Minecraft Crash Report ----
// Why did you do that?

Time: 27/06/21 09:06
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'bettercaves'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:437)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	Suppressed: java.lang.RuntimeException: java.lang.IllegalStateException: Key is not followed by an equals sign on line 1: 
		at me.shedaniel.cloth.clothconfig.shadowed.com.moandjiezana.toml.Toml.read(Toml.java:74)
		at me.shedaniel.autoconfig.serializer.Toml4jConfigSerializer.deserialize(Toml4jConfigSerializer.java:73)
		at me.shedaniel.autoconfig.ConfigManager.load(ConfigManager.java:92)
		at me.shedaniel.autoconfig.ConfigManager.<init>(ConfigManager.java:53)
		at me.shedaniel.autoconfig.AutoConfig.register(AutoConfig.java:66)
		at com.telepathicgrunt.repurposedstructures.RepurposedStructures.onInitialize(RepurposedStructures.java:43)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$2243/571421082.accept(Unknown Source)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
		... 11 more
	Caused by: java.lang.IllegalStateException: Key is not followed by an equals sign on line 1: 
		at me.shedaniel.cloth.clothconfig.shadowed.com.moandjiezana.toml.Toml.read(Toml.java:140)
		at me.shedaniel.cloth.clothconfig.shadowed.com.moandjiezana.toml.Toml.read(Toml.java:107)
		at me.shedaniel.cloth.clothconfig.shadowed.com.moandjiezana.toml.Toml.read(Toml.java:72)
		... 18 more
	Suppressed: com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonObject but was com.google.gson.JsonPrimitive
		at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:913)
		at com.google.gson.Gson.fromJson(Gson.java:887)
		at com.google.gson.Gson.fromJson(Gson.java:852)
		at com.google.gson.Gson.fromJson(Gson.java:801)
		at com.google.gson.Gson.fromJson(Gson.java:773)
		at ironfurnaces.config.Configuration.setup(Configuration.java:69)
		at ironfurnaces.config.Configuration.<init>(Configuration.java:52)
		at ironfurnaces.init.Reference.init(Reference.java:84)
		at ironfurnaces.IronFurnaces.onInitialize(IronFurnaces.java:15)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$2243/571421082.accept(Unknown Source)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
		... 11 more
Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: Key is not followed by an equals sign on line 1: 
	at me.shedaniel.cloth.clothconfig.shadowed.com.moandjiezana.toml.Toml.read(Toml.java:74)
	at me.shedaniel.autoconfig.serializer.Toml4jConfigSerializer.deserialize(Toml4jConfigSerializer.java:73)
	at me.shedaniel.autoconfig.ConfigManager.load(ConfigManager.java:92)
	at me.shedaniel.autoconfig.ConfigManager.<init>(ConfigManager.java:53)
	at me.shedaniel.autoconfig.AutoConfig.register(AutoConfig.java:66)
	at com.yungnickyoung.minecraft.bettercaves.init.BCModConfig.init(BCModConfig.java:18)
	at com.yungnickyoung.minecraft.bettercaves.BetterCaves.onInitialize(BetterCaves.java:57)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$2243/571421082.accept(Unknown Source)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	... 11 more
Caused by: java.lang.IllegalStateException: Key is not followed by an equals sign on line 1: 
	at me.shedaniel.cloth.clothconfig.shadowed.com.moandjiezana.toml.Toml.read(Toml.java:140)
	at me.shedaniel.cloth.clothconfig.shadowed.com.moandjiezana.toml.Toml.read(Toml.java:107)
	at me.shedaniel.cloth.clothconfig.shadowed.com.moandjiezana.toml.Toml.read(Toml.java:72)
	... 19 more

**Comment by ClosedTheDor** [comment]
and how to fix the XML_ERROR_PARSING_CDATA in minecraft

**Comment by ClosedTheDor** [comment]
09:24:02.463
BYG: "Load Complete" Event Complete!
09:24:41.178

---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 03/07/21 09:24
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'bettercaves'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:437)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	Suppressed: java.lang.RuntimeException: java.lang.IllegalStateException: Key is not followed by an equals sign on line 1: 
		at me.shedaniel.cloth.clothconfig.shadowed.com.moandjiezana.toml.Toml.read(Toml.java:74)
		at me.shedaniel.autoconfig.serializer.Toml4jConfigSerializer.deserialize(Toml4jConfigSerializer.java:73)
		at me.shedaniel.autoconfig.ConfigManager.load(ConfigManager.java:92)
		at me.shedaniel.autoconfig.ConfigManager.<init>(ConfigManager.java:53)
		at me.shedaniel.autoconfig.AutoConfig.register(AutoConfig.java:66)
		at com.telepathicgrunt.repurposedstructures.RepurposedStructures.onInitialize(RepurposedStructures.java:43)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$2243/1551923653.accept(Unknown Source)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
		... 11 more
	Caused by: java.lang.IllegalStateException: Key is not followed by an equals sign on line 1: 
		at me.shedaniel.cloth.clothconfig.shadowed.com.moandjiezana.toml.Toml.read(Toml.java:140)
		at me.shedaniel.cloth.clothconfig.shadowed.com.moandjiezana.toml.Toml.read(Toml.java:107)
		at me.shedaniel.cloth.clothconfig.shadowed.com.moandjiezana.toml.Toml.read(Toml.java:72)
		... 18 more
	Suppressed: com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonObject but was com.google.gson.JsonPrimitive
		at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:913)
		at com.google.gson.Gson.fromJson(Gson.java:887)
		at com.google.gson.Gson.fromJson(Gson.java:852)
		at com.google.gson.Gson.fromJson(Gson.java:801)
		at com.google.gson.Gson.fromJson(Gson.java:773)
		at ironfurnaces.config.Configuration.setup(Configuration.java:69)
		at ironfurnaces.config.Configuration.<init>(Configuration.java:52)
		at ironfurnaces.init.Reference.init(Reference.java:84)
		at ironfurnaces.IronFurnaces.onInitialize(IronFurnaces.java:15)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$2243/1551923653.accept(Unknown Source)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
		... 11 more
Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: Key is not followed by an equals sign on line 1: 
	at me.sargunvohra.mcmods.autoconfig1u.shadowed.com.moandjiezana.toml.Toml.read(Toml.java:74)
	at me.sargunvohra.mcmods.autoconfig1u.serializer.Toml4jConfigSerializer.deserialize(Toml4jConfigSerializer.java:55)
	at me.sargunvohra.mcmods.autoconfig1u.ConfigManager.load(ConfigManager.java:87)
	at me.sargunvohra.mcmods.autoconfig1u.ConfigManager.<init>(ConfigManager.java:53)
	at me.sargunvohra.mcmods.autoconfig1u.AutoConfig.register(AutoConfig.java:45)
	at com.yungnickyoung.minecraft.bettercaves.init.BCModConfig.init(BCModConfig.java:20)
	at com.yungnickyoung.minecraft.bettercaves.BetterCaves.onInitialize(BetterCaves.java:57)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$2243/1551923653.accept(Unknown Source)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	... 11 more
Caused by: java.lang.IllegalStateException: Key is not followed by an equals sign on line 1: 
	at me.sargunvohra.mcmods.autoconfig1u.shadowed.com.moandjiezana.toml.Toml.read(Toml.java:140)
	at me.sargunvohra.mcmods.autoconfig1u.shadowed.com.moandjiezana.toml.Toml.read(Toml.java:107)
	at me.sargunvohra.mcmods.autoconfig1u.shadowed.com.moandjiezana.toml.Toml.read(Toml.java:72)
	... 19 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:437)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3058142560 bytes (2916 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 2
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		added_origins_mod: Added Origins V2.0.0
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		artifacts: Artifacts 3.2.0+fabric
		autoconfig1u: Auto Config v1 Updated 3.3.1
		bedspreads: Bedspreads 1.3.1-1.16.4
		bettercaves: YUNG's Better Caves 1.16.5-1.1
		betterend: Better End 0.9.1-pre
		betternether: Better Nether 5.0.7
		blockus: Blockus 2.1.1+1.16.5
		blue_endless_jankson: jankson 1.2.0
		byg: BYG 1.1.7
		campfiresmelting: Campfire Smelting 1.0.0
		cardinal-components-base: Cardinal Components API (base) 2.8.3
		cardinal-components-entity: Cardinal Components API (entities) 2.8.3
		cardinal-components-item: Cardinal Components API (items) 2.7.10
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.8.3
		carrier: Carrier 1.7.5
		cavebiomes: Cave Biomes 0.6.2
		chime: Chime 1.1.3
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-config2: Cloth Config v4 4.11.19
		com_electronwill_night-config_core: core 3.6.0
		com_electronwill_night-config_toml: toml 3.6.0
		com_github_therandomlabs_trlutils-config: TRLUtils-Config master-SNAPSHOT
		com_github_therandomlabs_trlutils-fabric: TRLUtils-Fabric 1.16-SNAPSHOT
		crowdin-translate: CrowdinTranslate 1.3+1.16
		cubifortunarum: Cubi Fortunarum 1.0.1-1.16.5
		cultivation: Cultivation 0.0.72
		customportalapi: Custom Portals 0.0.1-beta32-1.16
		dark-enchanting: Dark Enchanting 0.1.1+mc.1.16.5
		decorative: Decorative 4.0.0
		extrablocks: Nico's Extra Blocks 0.1
		extraorigins: Extra Origins 1.16.5-11
		extrasponges: ExtraSponges 1.0.0
		fabric: Fabric API 0.33.0+1.16
		fabric-api-base: Fabric API Base 0.2.1+9354966b7d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.6+9354966b7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.5.0+kotlin.1.4.31
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.3.0+bc7a746f7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.4+9354966b7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.2+2868a2287d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+2868a2287d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabricloader: Fabric Loader 0.11.3
		fallflyinglib: FallFlyingLib 1.1.0
		fiber: fiber 0.23.0-2
		fiber2cloth: Fiber To Cloth 3.1.0
		go-fish: Go Fish 1.2.1-beta-1.16.4
		greater_eye: Greater Eye of Ender 1.1.5
		improved-stations: Improved Stations 2.0.3
		inventoryhud: Inventory HUD + 3.2.2
		inventorysorter: Inventory Sorter 1.7.9-1.16
		ironchest: Iron Chests 1.1.3
		ironfurnaces: Iron Furnaces 2.4.1
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		kyrptconfig: Kytpt Config 1.1.6-1.16
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.4.0+1.16.5
		lithium: Lithium 0.6.4
		locki: Locki 0.2.0
		magna: Magna 1.5.3-1.16.5
		maybe-data: Maybe data 1.0.0-1.16.2
		mcdar: MC Dungeons Artifacts 1.1.1
		midnight-hats: Midnight Hats 2.0.1
		minecraft: Minecraft 1.16.5
		miningutility: Mining Utility 1.0
		modmenu: Mod Menu 1.16.9
		mostructures: Mo' Structures 1.1.1+mc.1.16.5
		omega-config: OmegaConfig 1.0.4
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.1.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.1.0
		origins: Origins 0.7.1
		origins-classes: Origins: Classes 1.1.1
		pandamc_concreteplus: Concrete plus 1.8
		pehkui: Pehkui 2.1.0+21w18a
		phosphor: Phosphor 0.7.1+build.11
		physicsmod: Physics Mod 1.0.0
		playerabilitylib: Pal 1.2.2
		pptowers: Pew Pew Towers 1.0.2
		reach-entity-attributes: Reach Entity Attributes 1.1.1
		repurposed_structures: Repurposed Structures 1.16.5-1.10.1-fabric
		requiem: Requiem 1.7.12
		requiemapi: Requiem-API 1.7.12
		respawnablepets: Respawnable Pets 1.16.5-2
		roughlyenoughitems: Roughly Enough Items 5.11.202
		roughlyenoughitems-api: REI (API) 5.11.202
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.11.202
		roughlyenoughitems-runtime: REI (Runtime) 5.11.202
		satin: Satin 1.5.1
		seedy-behavior: Seedy Behavior 1.0.1
		show-off: Show Off 1.0.0-1.16.5
		sodium: Sodium 0.1.0
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stuffz: StuffZ 2.2.5
		team_reborn_energy: Energy 0.1.1
		the_aether: The Aether 1.16.5-1.4.1
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
		torohealth: ToroHealth Damage Indicators 1.16.4-fabric-4
		transportables: Transportables 1.0.1
		trinkets: Trinkets 2.6.7
		vanilla-hammers: Vanilla Hammers 3.0.3-1.16.5
		vanilladeathchest: VanillaDeathChest 1.16.3-1.11.0.7-fabric
		voyager: Voyager 1.0.0
		xaerominimap: Xaero's Minimap 21.7.0
		yungsapi: YUNG's API 1.16.5-Fabric-2
	Launched Version: fabric-loader-0.11.3-1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Jason\AppData\Roaming\.minecraft\crash-reports\crash-2021-07-03_09.24.13-client.txt
09:24:45.037
Process crashed with exit code -1

**Comment by yungnickyoung** [comment]
Please try updating Better Caves to 1.2.

**Comment by ClosedTheDor** [comment]
The problem is i have. 2 pc and they have the same mods

And before that doesent crash like that, i tthink is because of XML_ERROR_PARSING_CDATA

**Comment by ClosedTheDor** [comment]
I remeber that i fixed this a long time ago i just need to refresh my  memory
