### ISSUE TITLE
/help errors out when using Better Caves with a certain combination of mods

### ISSUE THREAD

**Issue by bluebear94** [yungnickyoung/Better-Caves#14]
Steps to reproduce:

I've managed to reproduce the error with the following mods:

* Minecraft 1.12.2
* Forge 14.23.5.2847
* Advent of Ascension 3.1.2b
* AppleCore 3.2.0
* AutoRegLib 1.3-32
* Baubles 1.5.2
* BetterFPS 1.4.8
* CodeChicken Lib 3.2.3.358
* CoFH Core 4.6.3.27
* CoFH World 1.3.1.7
* DungeonTactics 0.16.6
* FoamFix (version unknown)
* IvToolkit 1.3.3-1.12
* JEI Integration 1.5.1.36
* Just Enough Items 4.15.0.268
* Just Enough Resources 0.9.2
* Mantle 1.3.3.55
* McJtyLib 3.5.4
* Recurrent Complex 1.4.8.2
* Restone Flux 2.1.0.6
* Thermal Dynamics 2.5.5.21
* Thermal Expansion 5.5.4.43
* Thermal Foundation 2.6.3.27
* VanillaFix 1.0.10-SNAPSHOT
* YUNG's Better Caves 1.12.2-1.5.0

Then try using the `/help` command.

Expected: help output shows up

Actual: doesn't succeed; this error appears in the log:

```
[21:35:08] [Server thread/WARN] [net.minecraft.command.CommandHandler]: Couldn't process command: help
java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.ComparableTimSort.mergeHi(ComparableTimSort.java:866) ~[?:1.8.0_222]
	at java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:483) ~[?:1.8.0_222]
	at java.util.ComparableTimSort.mergeForceCollapse(ComparableTimSort.java:422) ~[?:1.8.0_222]
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:222) ~[?:1.8.0_222]
	at java.util.Arrays.sort(Arrays.java:1312) ~[?:1.8.0_222]
	at java.util.Arrays.sort(Arrays.java:1506) ~[?:1.8.0_222]
	at java.util.ArrayList.sort(ArrayList.java:1462) ~[?:1.8.0_222]
	at java.util.Collections.sort(Collections.java:141) ~[?:1.8.0_222]
	at net.minecraft.command.CommandHelp.getSortedPossibleCommands(SourceFile:116) ~[cn.class:?]
	at net.minecraft.command.CommandHelp.execute(SourceFile:71) ~[cn.class:?]
	at net.minecraft.command.CommandHandler.tryExecute(CommandHandler.java:119) [bj.class:?]
	at net.minecraft.command.CommandHandler.executeCommand(CommandHandler.java:91) [bj.class:?]
	at net.minecraft.network.NetHandlerPlayServer.handleSlashCommand(NetHandlerPlayServer.java:962) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processChatMessage(NetHandlerPlayServer.java:941) [pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.processPacket(SourceFile:37) [la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.processPacket(SourceFile:9) [la.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_222]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_222]
	at net.minecraft.util.Util.runTask(SourceFile:529) [h.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
[21:35:08] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] An unknown error occurred while attempting to perform this command
```

I don't think this is an issue with this mod's interaction with any single mod; it seems to be an issue with the number of items added by mods (e.g. removing either DungeonTactics or AoA3 causes the error to stop appearing). However, in my actual modpack with even more mods enabled, disabling YUNG's Better Caves allowed /help to succeed.

Edit: [full log](https://github.com/yungnickyoung/YUNGs-Better-Caves/files/3741941/2019-10-17-7.log.gz)

**Comment by yungnickyoung** [comment]
Now this is an odd one. If you could, do some testing and please make 100% sure that it's Better Caves causing the issue. I dug into the code where the error is happening, and basically it seems to be failing when trying to retrieve the list of commands. However, Better Caves does not add nor modify any commands in any way, so I can't see it being the cause of this bug.

**Comment by bluebear94** [comment]
Huh, tried again with the exact same set of mods, and the bug isn't there. Strange.

**Comment by bluebear94** [comment]
In fact, even when I enable all of the mods in my actual modpack, `/help` succeeds now.

**Comment by bluebear94** [comment]
After some searching, I found a report of the [same issue](https://www.curseforge.com/minecraft/mc-mods/dungeon-tactics/issues/105), but which mod is causing it is still unknown.

**Comment by yungnickyoung** [comment]
Looks like they weren't able to pinpoint the issue either. I'll leave this issue open in case you or someone else experiences this again. For now I'm gonna chalk it up to some odd behavior caused by other mod(s).
