### ISSUE TITLE
Dedicated server crash - Server Hangs

### ISSUE THREAD

**Issue by yungnickyoung** [yungnickyoung/Better-Caves#31]
"well, I just hit this crash on the server side while "exploring" at high speed. and by exploring, i mean, dashing really fast using a grapple hook across the terrain to get back home cause I got dropped into limbo by a dimension door and got out. :V
but yeah, something about a server tick and it references better caves a whole lot.
the crash goes away after it reloads, but it's happened twice so far."

```
---- Minecraft Crash Report ----
// You're mean.

Time: 2019-12-27 07:13:59 EST
Description: Watching Server

java.lang.Error: ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.getMaterial(BlockStateContainer.java:294)
    at com.yungnickyoung.minecraft.bettercaves.util.BetterCavesUtil.searchSurfaceAltitudeInRangeForColumn(BetterCavesUtil.java:251)
    at com.yungnickyoung.minecraft.bettercaves.util.BetterCavesUtil.getSurfaceAltitudeForColumn(BetterCavesUtil.java:229)
    at com.yungnickyoung.minecraft.bettercaves.util.BetterCavesUtil.getMaxSurfaceAltitudeSubChunk(BetterCavesUtil.java:215)
    at com.yungnickyoung.minecraft.bettercaves.world.MapGenBetterCaves.generate(MapGenBetterCaves.java:150)
    at net.minecraft.world.gen.ChunkGeneratorOverworld.generateChunk(ChunkGeneratorOverworld.java:211)
    at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:143)
    at net.minecraft.server.management.PlayerChunkMapEntry.providePlayerChunk(PlayerChunkMapEntry.java:126)
    at net.minecraft.server.management.PlayerChunkMap.tick(SourceFile:147)
    at net.minecraft.world.WorldServer.tick(WorldServer.java:227)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Thread Dump --
  Threads: "Chunk I/O Executor Thread-1" Id=206 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@1252fd7e
           at sun.misc.Unsafe.park(Native Method)
           -  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@1252fd7e
           at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
           at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
           at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
           at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
           at java.lang.Thread.run(Thread.java:748)
           
           
           "Netty Epoll Server IO #2" Id=202 RUNNABLE
           at io.netty.channel.epoll.Native.epollWait0(Native Method)
           at io.netty.channel.epoll.Native.epollWait(Native.java:117)
           at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:223)
           at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:247)
           at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
           at java.lang.Thread.run(Thread.java:748)
           
           
           "threadDeathWatcher-2-1" Id=201 TIMED_WAITING
           at java.lang.Thread.sleep(Native Method)
           at io.netty.util.ThreadDeathWatcher$Watcher.run(ThreadDeathWatcher.java:152)
           at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
           at java.lang.Thread.run(Thread.java:748)
           
           
           "Netty Epoll Server IO #1" Id=200 RUNNABLE
           at io.netty.channel.epoll.Native.epollWait0(Native Method)
           at io.netty.channel.epoll.Native.epollWait(Native.java:117)
           at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:223)
           at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:247)
           at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
           at java.lang.Thread.run(Thread.java:748)
           
           
           "BL Environment Event Overrides Downloader #0" Id=124 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@1c951144
           at sun.misc.Unsafe.park(Native Method)
           -  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@1c951144
           at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
           at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
           at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
           at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
           at java.lang.Thread.run(Thread.java:748)
           
           
           "File IO Thread" Id=112 TIMED_WAITING
           at java.lang.Thread.sleep(Native Method)
           at net.minecraft.world.storage.ThreadedFileIOBase.func_75736_b(SourceFile:51)
           at net.minecraft.world.storage.ThreadedFileIOBase.run(SourceFile:30)
           at java.lang.Thread.run(Thread.java:748)
           
           
           "Thread-51" Id=110 TIMED_WAITING
           at java.lang.Thread.sleep(Native Method)
           at thaumcraft.common.world.aura.AuraThread.run(AuraThread.java:79)
           at java.lang.Thread.run(Thread.java:748)
           
           
           "Thread-40" Id=99 TIMED_WAITING
           at java.lang.Thread.sleep(Native Method)
           at thaumcraft.common.world.aura.AuraThread.run(AuraThread.java:79)
           at java.lang.Thread.run(Thread.java:748)
           
           
           "Server Watchdog" Id=94 RUNNABLE
           at sun.management.ThreadImpl.dumpThreads0(Native Method)
           at sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:454)
           at net.minecraft.server.dedicated.ServerHangWatchdog.run(ServerHangWatchdog.java:45)
           at java.lang.Thread.run(Thread.java:748)
           
           
           "Netty Epoll Server IO #0" Id=59 RUNNABLE
           at io.netty.channel.epoll.Native.epollWait0(Native Method)
           at io.netty.channel.epoll.Native.epollWait(Native.java:117)
           at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:223)
           at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:247)
           at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
           at java.lang.Thread.run(Thread.java:748)
           
           
           "Keep-Alive-SocketCleaner" Id=55 WAITING on sun.net.www.http.KeepAliveStreamCleaner@18aa960e
           at java.lang.Object.wait(Native Method)
           -  waiting on sun.net.www.http.KeepAliveStreamCleaner@18aa960e
           at sun.net.www.http.KeepAliveStreamCleaner.run(KeepAliveStreamCleaner.java:101)
           at java.lang.Thread.run(Thread.java:748)
           
           
           "Server console handler" Id=30 RUNNABLE (in native)
           at java.io.FileInputStream.readBytes(Native Method)
           at java.io.FileInputStream.read(FileInputStream.java:255)
           at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
           at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
           -  locked java.io.BufferedInputStream@5da81b7f
           at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
           at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
           at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
           -  locked java.io.InputStreamReader@5814a4b9
           at java.io.InputStreamReader.read(InputStreamReader.java:184)
           ...
           
           
           "DestroyJavaVM" Id=29 RUNNABLE
           
           
           "Server thread" Id=27 RUNNABLE
           at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185904_a(BlockStateContainer.java:294)
           at com.yungnickyoung.minecraft.bettercaves.util.BetterCavesUtil.searchSurfaceAltitudeInRangeForColumn(BetterCavesUtil.java:251)
           at com.yungnickyoung.minecraft.bettercaves.util.BetterCavesUtil.getSurfaceAltitudeForColumn(BetterCavesUtil.java:229)
           at com.yungnickyoung.minecraft.bettercaves.util.BetterCavesUtil.getMaxSurfaceAltitudeSubChunk(BetterCavesUtil.java:215)
           at com.yungnickyoung.minecraft.bettercaves.world.MapGenBetterCaves.func_186125_a(MapGenBetterCaves.java:150)
           at net.minecraft.world.gen.ChunkGeneratorOverworld.func_185932_a(ChunkGeneratorOverworld.java:211)
           at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:143)
           at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
           ...
           
           
           "Server Infinisleeper" Id=26 TIMED_WAITING
           at java.lang.Thread.sleep(Native Method)
           at net.minecraft.server.dedicated.DedicatedServer$1.run(DedicatedServer.java:82)
           
           
           "Snooper Timer" Id=25 TIMED_WAITING on java.util.TaskQueue@6cbf81ce
           at java.lang.Object.wait(Native Method)
           -  waiting on java.util.TaskQueue@6cbf81ce
           at java.util.TimerThread.mainLoop(Timer.java:552)
           at java.util.TimerThread.run(Timer.java:505)
           
           
           "Thread-1" Id=24 WAITING on java.util.LinkedList@20e960b1
           at java.lang.Object.wait(Native Method)
           -  waiting on java.util.LinkedList@20e960b1
           at java.lang.Object.wait(Object.java:502)
           at com.zeitheron.hammercore.lib.zlib.utils.TaskedThread.run(TaskedThread.java:39)
           
           
           "Signal Dispatcher" Id=4 RUNNABLE
           
           
           "Finalizer" Id=3 WAITING on java.lang.ref.ReferenceQueue$Lock@3d87e430
           at java.lang.Object.wait(Native Method)
           -  waiting on java.lang.ref.ReferenceQueue$Lock@3d87e430
           at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
           at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
           at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:216)
           
           
           "Reference Handler" Id=2 WAITING on java.lang.ref.Reference$Lock@404bae55
           at java.lang.Object.wait(Native Method)
           -  waiting on java.lang.ref.Reference$Lock@404bae55
           at java.lang.Object.wait(Object.java:502)
           at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
           at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Linux (amd64) version 4.4.0-119-generic
  Java Version: 1.8.0_201, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 5020319648 bytes (4787 MB) / 6993477632 bytes (6669 MB) up to 7635730432 bytes (7282 MB)
  JVM Flags: 2 total; -Xmx8192M -Xms4096M
  IntCache: cache: 12, tcache: 94, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2847 127 mods loaded, 127 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                    | Version                  | Source                                          | Signature                                |
       |:------ |:--------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft             | 1.12.2                   | minecraft.jar                                   | None                                     |
       | LCHIJA | mcp                   | 9.42                     | minecraft.jar                                   | None                                     |
       | LCHIJA | FML                   | 8.0.99.99                | forge-1.12.2-14.23.5.2847-universal.jar         | None                                     |
       | LCHIJA | forge                 | 14.23.5.2847             | forge-1.12.2-14.23.5.2847-universal.jar         | None                                     |
       | LCHIJA | advancedrocketrycore  | 1                        | minecraft.jar                                   | None                                     |
       | LCHIJA | creativecoredummy     | 1.0.0                    | minecraft.jar                                   | None                                     |
       | LCHIJA | littletilescore       | 1.0.0                    | minecraft.jar                                   | None                                     |
       | LCHIJA | foamfixcore           | 7.7.4                    | minecraft.jar                                   | None                                     |
       | LCHIJA | randompatches         | 1.12.2-1.20.1.0          | randompatches-1.12.2-1.20.1.0.jar               | None                                     |
       | LCHIJA | actuallyadditions     | 1.12.2-r151              | ActuallyAdditions-1.12.2-r151-2.jar             | None                                     |
       | LCHIJA | redstoneflux          | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | cofhcore              | 4.6.3                    | CoFHCore-1.12.2-4.6.3.27-universal.jar          | None                                     |
       | LCHIJA | libvulpes             | 0.4.2.-69                | LibVulpes-1.12.2-0.4.2-69-universal.jar         | None                                     |
       | LCHIJA | advancedrocketry      | 1.6.0.-190               | AdvancedRocketry-1.12.2-1.6.0-190-universal.jar | None                                     |
       | LCHIJA | akashictome           | 1.2-12                   | AkashicTome-1.2-12.jar                          | None                                     |
       | LCHIJA | anvilpatch            | 1.0.0                    | anvilpatch-1.0.0.jar                            | None                                     |
       | LCHIJA | tammodized            | 0.15.6                   | TamModized-1.12.2-0.15.6.jar                    | None                                     |
       | LCHIJA | aov                   | 0.11.5                   | AoV-1.12-0.11.5.jar                             | None                                     |
       | LCHIJA | applecore             | 3.2.0                    | AppleCore-mc1.12.2-3.2.0.jar                    | None                                     |
       | LCHIJA | jei                   | 4.15.0.293               | jei_1.12.2-4.15.0.293.jar                       | None                                     |
       | LCHIJA | appleskin             | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                      | None                                     |
       | LCHIJA | quark                 | r1.6-177                 | Quark-r1.6-177.jar                              | None                                     |
       | LCHIJA | autoreglib            | 1.3-32                   | AutoRegLib-1.3-32.jar                           | None                                     |
       | LCHIJA | baubles               | 1.5.2                    | Baubles-1.12-1.5.2.jar                          | None                                     |
       | LCHIJA | bettercaves           | 1.12.2                   | bettercaves-1.12.2-1.6.0.jar                    | None                                     |
       | LCHIJA | bettercombatmod       | 1.5.6                    | BetterCombat-1.12.2-1.5.6.jar                   | None                                     |
       | LCHIJA | bibliocraft           | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar               | None                                     |
       | LCHIJA | blockcraftery         | 1.12.2-1.3.1             | blockcraftery-1.12.2-1.3.1.jar                  | None                                     |
       | LCHIJA | bonsaitrees           | 1.1.4                    | bonsaitrees-1.1.4-b170.jar                      | None                                     |
       | LCHIJA | bookshelf             | 2.3.590                  | Bookshelf-1.12.2-2.3.590.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | capsule               | 1.12.2-3.3.7             | Capsule-1.12.2-3.3.7.jar                        | None                                     |
       | LCHIJA | carryon               | 1.12.3                   | CarryOn MC1.12.2 v1.12.3.jar                    | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
       | LCHIJA | roots                 | 1.12.2-3.0.21            | Roots-1.12.2-3.0.21.jar                         | None                                     |
       | LCHIJA | mysticalworld         | 1.12.2-1.6.1             | mysticalworld-1.12.2-1.6.1.jar                  | None                                     |
       | LCHIJA | chisel                | MC1.12.2-1.0.1.44        | Chisel-MC1.12.2-1.0.1.44.jar                    | None                                     |
       | LCHIJA | chiselsandbits        | 14.33                    | chiselsandbits-14.33.jar                        | None                                     |
       | LCHIJA | sanlib                | 1.5.1                    | SanLib-1.12.2-1.5.1.jar                         | df48348748b5e141b1d118e2302a8d5be930b708 |
       | LCHIJA | claysoldiers          | 3.0.0-beta.2             | ClaySoldiersMod-1.12.2-3.0.0-beta.2.jar         | None                                     |
       | LCHIJA | clumps                | 3.1.2                    | Clumps-3.1.2.jar                                | None                                     |
       | LCHIJA | codechickenlib        | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | cofhworld             | 1.3.1                    | CoFHWorld-1.12.2-1.3.1.7-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | combatrefined         | 1.4.1                    | combatrefined-1.4.2.jar                         | None                                     |
       | LCHIJA | computercraft         | 1.80pr1                  | ComputerCraft1.80pr1.jar                        | None                                     |
       | LCHIJA | creativecore          | 1.9.9                    | CreativeCore_v1.9.83_mc1.12.2.jar               | None                                     |
       | LCHIJA | customstartinggear    | 1.2.0                    | CustomStartingGear-1.12-1.2.0.9-universal.jar   | None                                     |
       | LCHIJA | cyclicmagic           | 1.19.18                  | Cyclic-1.12.2-1.19.18.jar                       | None                                     |
       | LCHIJA | dimdoors              | 3.0.9+287                | DimensionalDoors-3.0.9-287.jar                  | None                                     |
       | LCHIJA | doggytalents          | 1.15.1.4                 | DoggyTalents-1.12.2-1.15.1.4-universal.jar      | None                                     |
       | LCHIJA | orelib                | 3.6.0.1                  | OreLib-1.12.2-3.6.0.1.jar                       | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | dsurround             | 3.6.0.2                  | DynamicSurroundings-1.12.2-3.6.0.2.jar          | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | eplus                 | 5.0.176                  | EnchantingPlus-1.12.2-5.0.176.jar               | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | environmentalcreepers | 1.5.0                    | environmentalcreepers-1.12.2-1.5.0.jar          | 2b03e1423915a189b8094816baa18f239d576dff |
       | LCHIJA | fastleafdecay         | v14                      | FastLeafDecay-v14.jar                           | None                                     |
       | LCHIJA | foamfix               | 0.10.10-1.12.2           | foamfix-0.10.10-1.12.2.jar                      | None                                     |
       | LCHIJA | forgelin              | 1.8.4                    | Forgelin-1.8.4.jar                              | None                                     |
       | LCHIJA | llibrary              | 1.7.19                   | llibrary-1.7.19-1.12.2.jar                      | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCHIJA | fossil                | 8.0.3                    | fossilsarcheology-8.0.3.jar                     | None                                     |
       | LCHIJA | hammercore            | 2.0.5.9                  | HammerCore-1.12.2-2.0.5.9.jar                   | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
       | LCHIJA | healthhungertweaks    | 3.0.1                    | healthhungertweaks-1.12.2-3.0.1-beta.jar        | None                                     |
       | LCHIJA | librarianlib          | 4.20                     | librarianlib-1.12.2-4.20-release.jar            | None                                     |
       | LCHIJA | hooked                | %VERSION%                | hooked-1.0.3.jar                                | None                                     |
       | LCHIJA | ichunutil             | 7.2.2                    | iChunUtil-1.12.2-7.2.2.jar                      | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHIJA | theoneprobe           | 1.4.28                   | theoneprobe-1.12-1.4.28.jar                     | None                                     |
       | LCHIJA | thermalfoundation     | 2.6.3                    | ThermalFoundation-1.12.2-2.6.3.27-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | immersiveengineering  | 0.12-92                  | ImmersiveEngineering-0.12-92.jar                | 4cb49fcde3b43048c9889e0a3d083225da926334 |
       | LCHIJA | immersivepetroleum    | 1.1.9                    | immersivepetroleum-1.12.2-1.1.9.jar             | None                                     |
       | LCHIJA | trackapi              | 1.2                      | TrackAPI-1.2.jar                                | None                                     |
       | LCHIJA | immersiverailroading  | 1.7.2                    | ImmersiveRailroading-1.7.2_1.12.2.jar           | None                                     |
       | LCHIJA | universalmodcore      | 1.0.0                    | ImmersiveRailroading-1.7.2_1.12.2.jar           | None                                     |
       | LCHIJA | immersivetech         | 1.3.10                   | immersivetech-1.12-1.3.10.jar                   | None                                     |
       | LCHIJA | inventorytweaks       | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                        | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCHIJA | kindredlegacy         | 1.12.2-pre-1.3_1         | kindredlegacy-1.12.2-pre-1.3_1.jar              | None                                     |
       | LCHIJA | lenientcreepers       | v1.0                     | lenientcreepers-1.12.x-v1.0.jar                 | None                                     |
       | LCHIJA | linear                | 1.2.2                    | Linear MC1.12.2 v1.2.2.jar                      | None                                     |
       | LCHIJA | littletiles           | 1.5.0                    | LittleTiles_v1.5.0-pre189_mc1.12.2.jar          | None                                     |
       | LCHIJA | malisiscore           | 1.12.2-6.5.1-SNAPSHOT    | malisiscore-1.12.2-6.5.1.jar                    | None                                     |
       | LCHIJA | maxpotidext           | 1.0.3                    | maxpotidext-1.0.3.jar                           | b851b8b7c7f4d8d0e910ff27618150ba80c026ec |
       | LCHIJA | micwands              | 1.0.4                    | MobControlWands_1.12.2-1.0.4.jar                | None                                     |
       | LCHIJA | numina                | 1.12.2-1.0.38            | Numina-1.12.2-1.0.38.jar                        | None                                     |
       | LCHIJA | thaumcraft            | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar                | None                                     |
       | LCHIJA | powersuits            | 1.12.2-1.0.46            | ModularPowersuits-1.12.2-1.0.46.jar             | None                                     |
       | LCHIJA | mowziesmobs           | 1.5.4                    | mowziesmobs-1.5.4.jar                           | None                                     |
       | LCHIJA | thermalexpansion      | 5.5.4                    | ThermalExpansion-1.12.2-5.5.4.43-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | omlib                 | 3.1.3-246                | omlib-1.12.2-3.1.3-246.jar                      | None                                     |
       | LCHIJA | openmodularturrets    | 3.1.4-356                | openmodularturrets-1.12.2-3.1.4-356.jar         | None                                     |
       | LCHIJA | oreexcavation         | 1.4.143                  | OreExcavation-1.4.143.jar                       | None                                     |
       | LCHIJA | harvestcraft          | 1.12.2zb                 | Pam's HarvestCraft 1.12.2zf.jar                 | None                                     |
       | LCHIJA | patchouli             | 1.0-20                   | Patchouli-1.0-20.jar                            | None                                     |
       | LCHIJA | potioncore            | 1.8_for_1.12.2           | PotionCore-1.8_for_1.12.2.jar                   | None                                     |
       | LCHIJA | potioncraft           | 1.1.1                    | potioncraft-1.1.1.jar                           | None                                     |
       | LCHIJA | projecte              | 1.12.2-PE1.4.1           | ProjectE-1.12.2-PE1.4.1.jar                     | None                                     |
       | LCHIJA | randomthings          | 4.2.7.3                  | RandomThings-MC1.12.2-4.2.7.3.jar               | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCHIJA | sanplayermodel        | 1.1.1                    | SanLib-1.12.2-1.5.1.jar                         | None                                     |
       | LCHIJA | selim_enchants        | 2.1.1                    | Selim's Enchantments-1.12.2-2.1.1.jar           | None                                     |
       | LCHIJA | sgcraft               | 1.13.2                   | SGCraft-2.0.2.jar                               | None                                     |
       | LCHIJA | silentlib             | 3.0.13                   | SilentLib-1.12.2-3.0.13+167.jar                 | None                                     |
       | LCHIJA | silentgems            | 2.8.18                   | SilentsGems-1.12.2-2.8.22+327.jar               | None                                     |
       | LCHIJA | sgextraparts          | 1.4.6                    | SGExtraParts-1.12.2-1.4.6-49.jar                | None                                     |
       | LCHIJA | spartanshields        | 1.5.4                    | SpartanShields-1.12.2-1.5.4.jar                 | None                                     |
       | LCHIJA | spartanweaponry       | beta 1.3.8               | SpartanWeaponry-1.12.2-beta-1.3.8.jar           | None                                     |
       | LCHIJA | specialai             | 1.1.0_for_mc1.12.2       | specialai-1.1.0_for_mc1.12.2.jar                | None                                     |
       | LCHIJA | spiceoflife           | 1.3.12                   | SpiceOfLife-mc1.12-1.3.12.jar                   | None                                     |
       | LCHIJA | surge                 | 2.0.77                   | Surge-1.12.2-2.0.77.jar                         | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | sync                  | 7.1.0                    | Sync-1.12.2-7.1.0.jar                           | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHIJA | thaumadditions        | 22r                      | ThaumicAdditions-1.12.2-22r.jar                 | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | LCHIJA | tcinventoryscan       | 2.0.10                   | ThaumicInventoryScanning_1.12.2-2.0.10.jar      | None                                     |
       | LCHIJA | thaumicperiphery      | 0.3.1                    | thaumicperiphery-0.3.1.jar                      | None                                     |
       | LCHIJA | thermalconversion     | 2.0                      | ThermalConversion-1.12.2-2.0.jar                | None                                     |
       | LCHIJA | thermaldynamics       | 2.5.5                    | ThermalDynamics-1.12.2-2.5.5.21-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | thermalinnovation     | 0.3.3                    | ThermalInnovation-1.12.2-0.3.3.12-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | tombmanygraves        | 1.12-4.2.0               | TombManyGraves-1.12-4.2.0.jar                   | None                                     |
       | LCHIJA | totemic               | 1.12.2-0.11.6            | Totemic-1.12.2-0.11.6.jar                       | 21d11d7bf4d97b465382a1f95428029aac6daaea |
       | LCHIJA | traverse              | 1.6.0                    | Traverse-1.12.2-1.6.0-69.jar                    | None                                     |
       | LCHIJA | natural_absorption    | 1.2.2                    | unnatural_absorption-1.12-1.3.1.jar             | None                                     |
       | LCHIJA | vanillafix            | 1.0.10-SNAPSHOT          | VanillaFix-1.0.10-99.jar                        | None                                     |
       | LCHIJA | kiwi                  | 0.5.3.32                 | Kiwi-1.12.2-0.5.3.32.jar                        | None                                     |
       | LCHIJA | cuisine               | 0.5.17-build909          | Cuisine-0.5.17-build909.jar                     | None                                     |
       | LCHIJA | vanillafoodpantry     | 4.3.1                    | vanillafoodpantry-mc1.12.2-4.3.1.jar            | None                                     |
       | LCHIJA | vanillasatchels       | 1.0.2                    | VanillaSatchels-1.12.2-1.0.2.4-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | vanillatools          | 1.1.0                    | VanillaTools-1.12.2-1.1.0.2-universal.jar       | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | vc                    | 5.9.13                   | ViesCraft-1.12.2-5.9.13.jar                     | None                                     |
       | LCHIJA | walljump              | 1.12.2-1.2.3             | walljump-1.12.2-1.2.3.jar                       | None                                     |
       | LCHIJA | thebetweenlands       | 3.5.4                    | TheBetweenlands-3.5.4-universal.jar             | 38067d6878811efb38b6a045521cfd80b9b60b38 |
       | LCHIJA | solcarrot             | 1.8.3                    | solcarrot-1.12.2-1.8.3.jar                      | None                                     |
       | LCHIJA | phosphor-lighting     | 1.12.2-0.2.6             | phosphor-1.12.2-0.2.6+build50-universal.jar     | f0387d288626cc2d937daa504e74af570c52a2f1 |
       | LCHIJA | librarianliblate      | 4.20                     | librarianlib-1.12.2-4.20-release.jar            | None                                     |
       | LCHIJA | mysticallib           | 1.12.2-1.4.0             | mysticallib-1.12.2-1.4.0.jar                    | None                                     |
  Loaded coremods (and transformers): Quark Plugin (Quark-r1.6-177.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
                                        squeek.applecore.asm.TransformerModuleHandler
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      RandomPatches (randompatches-1.12.2-1.20.1.0.jar)
                                        com.therandomlabs.randompatches.core.RPTransformer
                                      TransformLoader (DynamicSurroundings-1.12.2-3.6.0.2.jar)
                                        
                                      HCASM (HammerCore-1.12.2-2.0.5.9.jar)
                                        com.zeitheron.hammercore.asm.HammerCoreTransformer
                                      LittlePatchingLoader (LittleTiles_v1.5.0-pre189_mc1.12.2.jar)
                                        com.creativemd.littletiles.LittleTilesTransformer
                                      TheBetweenlandsLoadingPlugin (TheBetweenlands-3.5.4-core.jar)
                                        thebetweenlands.core.TheBetweenlandsClassTransformer
                                      IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
                                        blusunrize.immersiveengineering.common.asm.IEClassTransformer
                                      CreativePatchingLoader (CreativeCore_v1.9.83_mc1.12.2.jar)
                                        
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      LibrarianLib Plugin (librarianlib-1.12.2-4.20-release.jar)
                                        com.teamwizardry.librarianlib.asm.LibLibTransformer
                                      Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
                                        
                                      LoadingPlugin (RandomThings-MC1.12.2-4.2.7.3.jar)
                                        lumien.randomthings.asm.ClassTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
                                        
                                      SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
                                        
                                      AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.6.0-190-universal.jar)
                                        zmaster587.advancedRocketry.asm.ClassTransformer
                                      Max Potion ID Extender (maxpotidext-1.0.3.jar)
                                        zabi.minecraft.maxpotidext.MPIDTransformer
  HammerCore Debug Information: Dependent Mods:
                                    -Thaumic Additions: Reconstructed (thaumadditions) @22r
  Suspected Mods: YUNG's Better Caves (bettercaves)
  Profiler Position: N/A (disabled)
  Player Count: 1 / 20; [EntityPlayerMP['Darkmega18'/41, l='The Three Adventurers', x=677.66, y=85.58, z=785.98]]
  Is Modded: Definitely; Server brand changed to 'fml,forge'
  Type: Dedicated Server (map_server.txt)
```

**Comment by yungnickyoung** [comment]
Unsure about this one. Never heard anything else about it, and the code has since undergone a major refactor.
