### ISSUE TITLE
1.16.4 worldgen stalling

### ISSUE THREAD

**Issue by Raycoms** [yungnickyoung/Better-Caves#92]
Getting regular stalls of the worldgen with locks.

```
"Worker-Main-215" Id=387 RUNNABLE
    at com.yungnickyoung.minecraft.bettercaves.noise.FastNoise.SingleCubicFractalRigidMulti(FastNoise.java:1523)
    at com.yungnickyoung.minecraft.bettercaves.noise.FastNoise.GetNoise(FastNoise.java:496)
    at com.yungnickyoung.minecraft.bettercaves.noise.NoiseGen.generateNoiseColumn(NoiseGen.java:68)
    at com.yungnickyoung.minecraft.bettercaves.noise.NoiseGen.interpolateNoiseCube(NoiseGen.java:160)
    at com.yungnickyoung.minecraft.bettercaves.world.carver.controller.CaveCarverController.carveChunk(CaveCarverController.java:207)
    at com.yungnickyoung.minecraft.bettercaves.world.carver.BetterCavesCarver.carve(BetterCavesCarver.java:73)
```

Is the only thing that runs on a separate thread in this moment.

**Comment by yungnickyoung** [comment]
Can you provide some more info? Forge version, other mods you're using, etc.

I'm pretty confused at this because there's no way FastNoise is deadlocking

**Comment by Raycoms** [comment]
Might be just an coincidence potentially.

https://gist.github.com/Raycoms/2f3c3edc9047d3f4bd689a17c0b87b3a

A full log with all additional mods and forge version

**Comment by yungnickyoung** [comment]
Yeah sorry, can't help too much there. It's definitely not Better Caves though.

If I'm reading the logs right, it looks like someone opened a chest containing a buried treasure map right when the crash happened. Not sure if it's related but that's somewhere to start looking, if you have any mods related to that.

**Comment by Raycoms** [comment]
okay ty =)
