### ISSUE TITLE
Startup crash

### ISSUE THREAD

**Issue by ApolloReaper** [yungnickyoung/Better-Caves#95]
[02:20:09] [main/INFO]: ModLauncher running: args [--username, ApolloReaper, --version, forge-34.1.42, --gameDir, C:\Users\Marc\Twitch\Minecraft\Instances\new, --assetsDir, C:\Users\Marc\Twitch\Minecraft\Install\assets, --assetIndex, 1.16, --uuid, 4d092e8cb2824c518c39e806634c9358, --accessToken, ????????, --userType, mojang, --versionType, release, --width, 1024, --height, 768, --launchTarget, fmlclient, --fml.forgeVersion, 34.1.42, --fml.mcVersion, 1.16.3, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20201025.185957]
[02:20:09] [main/INFO]: ModLauncher 8.0.6+85+master.325de55 starting: java version 1.8.0_51 by Oracle Corporation
[02:20:09] [main/WARN]: LEGACY JDK DETECTED, SECURED JAR HANDLING DISABLED
[02:20:09] [main/INFO]: Added Lets Encrypt root certificates as additional trust
[02:20:09] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/Marc/Twitch/Minecraft/Install/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=CLIENT
[02:20:12] [main/INFO]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 1:0 token recognition error at: '/'
[02:20:12] [main/INFO]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 1:1 token recognition error at: '/'
[02:20:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config bettercaves.mixins.json
[02:20:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
[02:20:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
[02:20:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
[02:20:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.addConfig(MixinPlatformManager.java:263)
[02:20:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformAgentDefault.prepare(MixinPlatformAgentDefault.java:46)
[02:20:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinContainer.prepare(MixinContainer.java:122)
[02:20:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.createContainerFor(MixinPlatformManager.java:145)
[02:20:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.addContainer(MixinPlatformManager.java:135)
[02:20:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.addNestedContainers(MixinPlatformManager.java:153)
[02:20:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.scanForContainers(MixinPlatformManager.java:214)
[02:20:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:187)
[02:20:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:190)
[02:20:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinLaunchPlugin.initializeLaunch(MixinLaunchPlugin.java:196)
[02:20:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$9(LaunchPluginHandler.java:97)
[02:20:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchPluginHandler$$Lambda$432/992457879.accept(Unknown Source)
[02:20:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.HashMap.forEach(HashMap.java:1280)
[02:20:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:97)
[02:20:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:52)
[02:20:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[02:20:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[02:20:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[02:20:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.IllegalArgumentException: The specified resource 'bettercaves.mixins.json' was invalid or could not be read
[02:20:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1082)
[02:20:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
[02:20:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 20 more

**Comment by yungnickyoung** [comment]
Can't help you if you don't provide any information. Also, update to the latest version.

**Comment by ApolloReaper** [comment]
so no crash logs are generated as it happens strait on startup and i am using the latest ver of the mod 1.16.3-106 for 1.16.3 forge

**Comment by yungnickyoung** [comment]
What other mods are you using?

**Comment by ApolloReaper** [comment]
well need to apologize, i fixed the issue my self, so the curseforge app i use to play mc modded apparently keeps every mod file u update, so i had several dif ver of a bunch of mods and didnt realize until i started taking screen shots of the mod folder, so looks like its a bug on their part

**Comment by yungnickyoung** [comment]
No worries, glad you figured it out
